### ISSUE TITLE
sha256_update8x slower than expected

### ISSUE THREAD

**Issue by OussamaDanba** [sphincs/sphincsplus#1]
Using linux `perf` to profile I currently measure sha256_update8x to take about 9-10% (9.76% specifically) of the total time. Looking at the generated assembly it seems that memcpy is the bottleneck in this function.
Interestingly, changing memcpy to memmove (which is expected to be slower) reduces sha256_update8x to take about 1-2% (1.37% specifically) of the total time. Looking at that assembly shows that it calls glibc rather than doing it inline.

I observe this behavior on the following platforms (all set to a single core with a fixed frequency):
- Intel i5-8250u using Arch Linux
- Intel i5-4460 using Debian
- AMD r5 1600 using Ubuntu

Initially I expected `perf` to not measure the calls to glibc but the built-in benchmark (which uses the cycle counter) shows that there is indeed an improvement matching what `perf` reported.

Output with memcpy:
```
Parameters: n = 32, h = 64, d = 8, b = 14, k = 22, w = 16
Running 10 iterations.
Generating keypair.. avg.   247850.48 us (0.25 sec); median    446,894,147 cycles,      1x:    446,894,147 cycles
  - WOTS pk gen..    avg.      903.39 us (0.00 sec); median      1,621,072 cycles,    256x:    414,994,432 cycles
Signing..            avg.  2886344.25 us (2.89 sec); median  5,352,747,435 cycles,      1x:  5,352,747,435 cycles
  - FORS signing..   avg.   894149.36 us (0.89 sec); median  1,612,681,974 cycles,      1x:  1,612,681,974 cycles
  - WOTS signing..   avg.       87.48 us (0.00 sec); median        156,892 cycles,      8x:      1,255,136 cycles
  - WOTS pk gen..    avg.      907.55 us (0.00 sec); median      1,651,092 cycles,   2048x:  3,381,436,416 cycles
Verifying..          avg.    11163.45 us (0.01 sec); median     40,992,378 cycles,      1x:     40,992,378 cycles
Signature size: 29792 (29.09 KiB)
Public key size: 64 (0.06 KiB)
Secret key size: 128 (0.12 KiB)
```

Output with memmove:
```
Parameters: n = 32, h = 64, d = 8, b = 14, k = 22, w = 16
Running 10 iterations.
Generating keypair.. avg.   232337.44 us (0.23 sec); median    419,017,549 cycles,      1x:    419,017,549 cycles
  - WOTS pk gen..    avg.      838.53 us (0.00 sec); median      1,509,783 cycles,    256x:    386,504,448 cycles
Signing..            avg.  2705637.84 us (2.71 sec); median  5,021,943,488 cycles,      1x:  5,021,943,488 cycles
  - FORS signing..   avg.   837526.53 us (0.84 sec); median  1,511,390,594 cycles,      1x:  1,511,390,594 cycles
  - WOTS signing..   avg.       87.87 us (0.00 sec); median        157,444 cycles,      8x:      1,259,552 cycles
  - WOTS pk gen..    avg.      837.10 us (0.00 sec); median      1,506,140 cycles,   2048x:  3,084,574,720 cycles
Verifying..          avg.    11371.54 us (0.01 sec); median     20,489,610 cycles,      1x:     20,489,610 cycles
Signature size: 29792 (29.09 KiB)
Public key size: 64 (0.06 KiB)
Secret key size: 128 (0.12 KiB)
```

I'm not quite sure what is causing inline memcpy to be so much slower but it seems worth looking into.

**Comment by cryptojedi** [comment]
Oussama Danba <notifications@github.com> wrote:
> Using linux `perf` to profile I currently measure sha256_update8x to
> take about 9-10% (9.76% specifically) of the total time. Looking at
> the generated assembly it seems that memcpy is the bottleneck in this
> function.
> Interestingly, changing memcpy to memmove (which is expected to be
> slower) reduces sha256_update8x to take about 1-2% (1.37%
> specifically) of the total time. Looking at that assembly shows that
> it calls glibc rather than doing it inline.

What version of gcc did you use?

**Comment by bwesterb** [comment]
Over the years, there have been some major improvements. On a i7-4790 on the #18 branch I get:

```
Parameters: n = 32, h = 64, d = 8, b = 14, k = 22, w = 16
Running 10 iterations.
Generating keypair.. avg.    68222.24 us (0.07 sec); median    244,034,866 cycles,      1x:    244,034,866 cycles
  - WOTS pk gen 8x.. avg.     2125.09 us (0.00 sec); median      7,614,574 cycles,     32x:    243,666,368 cycles
Signing..            avg.   796923.11 us (0.80 sec); median  2,863,578,903 cycles,      1x:  2,863,578,903 cycles
  - FORS signing..   avg.   253608.00 us (0.25 sec); median    910,784,263 cycles,      1x:    910,784,263 cycles
  - WOTS pk gen x8.. avg.     2126.39 us (0.00 sec); median      7,611,232 cycles,    256x:  1,948,475,392 cycles
Verifying..          avg.     1954.40 us (0.00 sec); median      6,981,756 cycles,      1x:      6,981,756 cycles
```

Only 1.15% is spent in (the successor of) update8x.

**Comment by bwesterb** [comment]
I presume we can consider the issue fixed?
