### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by bwesterb** [sphincs/sphincsplus#19]
We should get rid of the global variables so that it's thread safe.

**Comment by bwesterb** [comment]
@thomwiggers Perhaps we should coordinate to prevent even more double work :).

**Comment by thomwiggers** [comment]
For reference: the problem: https://github.com/sphincs/sphincsplus/blob/master/ref/hash_haraka.c#L11-L15

**Comment by bwesterb** [comment]
There are more, such as `state_seed` for sha256-avx.

**Comment by thomwiggers** [comment]
Yeah that's the other one — but it's just `initialize_hash_function` that's the problem because that's the only place where `state_seed` is called AFAIK.

**Comment by bwesterb** [comment]
Proposal: carry around a pointer to a context structure, which contains the formerly global state.  We can also move in pub_seed, sk_seed, etc.
