### ISSUE TITLE
Dual licensing

### ISSUE THREAD

**Issue by dstebila** [sphincs/sphincsplus#49]
In liboqs we've gotten some feedback (https://github.com/open-quantum-safe/liboqs/issues/1437) that the CC0 license is a barrier to adoption by some distributions. Would SPHINCS+ be willing to consider dual licensing to add another license?  See also https://github.com/open-quantum-safe/liboqs/issues/1388#issuecomment-1430046692 for comments from the Fedora team.

**Comment by dstebila** [comment]
Just checking to see if there's been any progress on this front.

**Comment by bwesterb** [comment]
The team seems happy to accommodate Fedora, but we're still discussing which exact combination of licenses to use.

**Comment by MrPugh** [comment]
I added a [branch 'license'](/sphincs/sphincsplus/tree/license) to tackle the issue; please check and comment.

**Comment by MrPugh** [comment]
I am not sure how to handle the NIST files:

  ref/PQCgenKAT_sign.c
  ref/rng.c
  ref/rng.h
