### ISSUE TITLE
SPHINCS+ v.3 vs v.3.1 submissions

### ISSUE THREAD

**Issue by livebe01** [sphincs/sphincsplus#58]
The Readme for this project states
> This repository contains the software that accompanies the [SPHINCS+ submission](https://sphincs.org/) to [NIST's Post-Quantum Cryptography](https://csrc.nist.gov/Projects/Post-Quantum-Cryptography) project.

The FIPS 205 IPD references v.3 and v.3.1 SPHINCS+ submissions. Does the master branch of this project represent the v.3.1 submission?

Thanks!

**Comment by bwesterb** [comment]
The master branch is [on v3.1](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/Ca4zQeyObOY/m/j1D4HI2cAAAJ).
